const sampleJobData = [
  {
    title: "Software Engineer",
    salary: "PHP 80,000 - PHP 100,000",
    company: "Tech Innovators Inc.",
    time: "Full-time",
    location: "Makati City, Philippines",
    description: "We are looking for a skilled software engineer who can develop scalable applications and collaborate with cross-functional teams.",
    link: "/job/software-engineer",
  },
  {
    title: "Data Analyst",
    salary: "PHP 60,000 - PHP 75,000",
    company: "Data Insights PH",
    time: "Part-time",
    location: "Quezon City, Philippines",
    description: "Analyze complex datasets to provide actionable insights. Knowledge of SQL, Python, and data visualization tools is required.",
    link: "/job/data-analyst",
  },
  {
    title: "Product Manager",
    salary: "PHP 90,000 - PHP 120,000",
    company: "Innovatech Solutions",
    time: "Full-time",
    location: "Remote",
    description: "Lead product development from ideation to launch. Strong communication and organizational skills are essential.",
    link: "/job/product-manager",
  },
  {
    title: "UX Designer",
    salary: "PHP 70,000 - PHP 85,000",
    company: "Creative Minds Studio",
    time: "Full-time",
    location: "Cebu City, Philippines",
    description: "Design user-centric interfaces and experiences. Proficiency in Figma, Adobe XD, and user research methodologies is required.",
    link: "/job/ux-designer",
  },
  {
    title: "Marketing Specialist",
    salary: "PHP 50,000 - PHP 65,000",
    company: "Brand Builders Co.",
    time: "Full-time",
    location: "Taguig City, Philippines",
    description: "Develop and implement marketing strategies to enhance brand visibility. Experience in digital marketing and SEO is a plus.",
    link: "/job/marketing-specialist",
  },
  {
    title: "DevOps Engineer",
    salary: "PHP 85,000 - PHP 110,000",
    company: "CloudOps Solutions",
    time: "Full-time",
    location: "Pasig City, Philippines",
    description: "Implement and manage CI/CD pipelines, monitor system performance, and ensure infrastructure scalability.",
    link: "/job/devops-engineer",
  },
  {
    title: "Graphic Designer",
    salary: "PHP 45,000 - PHP 60,000",
    company: "Creative Edge Agency",
    time: "Part-time",
    location: "Davao City, Philippines",
    description: "Create visually appealing designs for digital and print media. Proficiency in Adobe Creative Suite is required.",
    link: "/job/graphic-designer",
  },
  {
    title: "Customer Support Specialist",
    salary: "PHP 40,000 - PHP 50,000",
    company: "HelpDesk Heroes",
    time: "Full-time",
    location: "Cagayan de Oro, Philippines",
    description: "Provide exceptional customer support via phone, email, and chat. Strong communication skills are essential.",
    link: "/job/customer-support-specialist",
  },
  {
    title: "Business Analyst",
    salary: "PHP 70,000 - PHP 90,000",
    company: "Enterprise Solutions Inc.",
    time: "Full-time",
    location: "Manila, Philippines",
    description: "Analyze business processes and recommend solutions to improve efficiency. Experience with data analysis tools is a plus.",
    link: "/job/business-analyst",
  },
  {
    title: "Content Writer",
    salary: "PHP 35,000 - PHP 50,000",
    company: "Wordsmith Agency",
    time: "Part-time",
    location: "Remote",
    description: "Write engaging and SEO-friendly content for blogs, websites, and social media. Strong writing skills are required.",
    link: "/job/content-writer",
  },
];

export default sampleJobData;